name: Release (tagged)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer
          extensions: mbstring, intl, json, xml, curl, zip

      - name: Install production dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Build zip
        run: |
          tools/build-plugin-zip.sh \
            --slug fp-esperienze \
            --out-dir dist

      - name: Compute checksum
        run: |
          cd dist
          for f in *.zip; do
            sha256sum "$f" > "$f.sha256"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*.zip
            dist/*.zip.sha256
